// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverMessageSystem.proto

#include "serverMessageSystem.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_serverMessageSystem_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GameType_serverMessageSystem_2eproto;
namespace serverMessageSystem {
class GameTypeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameType> _instance;
} _GameType_default_instance_;
class ClientEnteringRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientEnteringRequest> _instance;
} _ClientEnteringRequest_default_instance_;
}  // namespace serverMessageSystem
static void InitDefaultsGameType_serverMessageSystem_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serverMessageSystem::_GameType_default_instance_;
    new (ptr) ::serverMessageSystem::GameType();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serverMessageSystem::GameType::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GameType_serverMessageSystem_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGameType_serverMessageSystem_2eproto}, {}};

static void InitDefaultsClientEnteringRequest_serverMessageSystem_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::serverMessageSystem::_ClientEnteringRequest_default_instance_;
    new (ptr) ::serverMessageSystem::ClientEnteringRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::serverMessageSystem::ClientEnteringRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ClientEnteringRequest_serverMessageSystem_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsClientEnteringRequest_serverMessageSystem_2eproto}, {
      &scc_info_GameType_serverMessageSystem_2eproto.base,}};

void InitDefaults_serverMessageSystem_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_GameType_serverMessageSystem_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ClientEnteringRequest_serverMessageSystem_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_serverMessageSystem_2eproto[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_serverMessageSystem_2eproto[2];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_serverMessageSystem_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_serverMessageSystem_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::GameType, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::GameType, hasaddonwildaxe_),
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::GameType, hasaddonclericalerrors_),
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::GameType, rulestype_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::ClientEnteringRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::ClientEnteringRequest, messageid_),
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::ClientEnteringRequest, clientname_),
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::ClientEnteringRequest, enteringrequest_),
  PROTOBUF_FIELD_OFFSET(::serverMessageSystem::ClientEnteringRequest, gametype_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::serverMessageSystem::GameType)},
  { 8, -1, sizeof(::serverMessageSystem::ClientEnteringRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::serverMessageSystem::_GameType_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::serverMessageSystem::_ClientEnteringRequest_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_serverMessageSystem_2eproto = {
  {}, AddDescriptors_serverMessageSystem_2eproto, "serverMessageSystem.proto", schemas,
  file_default_instances, TableStruct_serverMessageSystem_2eproto::offsets,
  file_level_metadata_serverMessageSystem_2eproto, 2, file_level_enum_descriptors_serverMessageSystem_2eproto, file_level_service_descriptors_serverMessageSystem_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_serverMessageSystem_2eproto = {
  false, InitDefaults_serverMessageSystem_2eproto, 
  "\n\031serverMessageSystem.proto\022\023serverMessa"
  "geSystem\"v\n\010GameType\022\027\n\017hasAddonWildAxe\030"
  "\001 \001(\010\022\036\n\026hasAddonClericalErrors\030\002 \001(\010\0221\n"
  "\trulesType\030\003 \001(\0162\036.serverMessageSystem.R"
  "ulesType\"\262\001\n\025ClientEnteringRequest\022\021\n\tme"
  "ssageID\030\001 \001(\r\022\022\n\nclientName\030\002 \001(\t\022A\n\017ent"
  "eringRequest\030\003 \001(\0162(.serverMessageSystem"
  ".GameCreationRequest\022/\n\010gameType\030\004 \001(\0132\035"
  ".serverMessageSystem.GameType*&\n\tRulesTy"
  "pe\022\r\n\tAutomatic\020\000\022\n\n\006Manual\020\001*9\n\023GameCre"
  "ationRequest\022\017\n\013JoinTheGame\020\000\022\021\n\rCreateT"
  "heGame\020\001b\006proto3"
,
  "serverMessageSystem.proto", &assign_descriptors_table_serverMessageSystem_2eproto, 456,
};

void AddDescriptors_serverMessageSystem_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_serverMessageSystem_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_serverMessageSystem_2eproto = []() { AddDescriptors_serverMessageSystem_2eproto(); return true; }();
namespace serverMessageSystem {
const ::google::protobuf::EnumDescriptor* RulesType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_serverMessageSystem_2eproto);
  return file_level_enum_descriptors_serverMessageSystem_2eproto[0];
}
bool RulesType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* GameCreationRequest_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_serverMessageSystem_2eproto);
  return file_level_enum_descriptors_serverMessageSystem_2eproto[1];
}
bool GameCreationRequest_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void GameType::InitAsDefaultInstance() {
}
class GameType::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameType::kHasAddonWildAxeFieldNumber;
const int GameType::kHasAddonClericalErrorsFieldNumber;
const int GameType::kRulesTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameType::GameType()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serverMessageSystem.GameType)
}
GameType::GameType(const GameType& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&hasaddonwildaxe_, &from.hasaddonwildaxe_,
    static_cast<size_t>(reinterpret_cast<char*>(&rulestype_) -
    reinterpret_cast<char*>(&hasaddonwildaxe_)) + sizeof(rulestype_));
  // @@protoc_insertion_point(copy_constructor:serverMessageSystem.GameType)
}

void GameType::SharedCtor() {
  ::memset(&hasaddonwildaxe_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rulestype_) -
      reinterpret_cast<char*>(&hasaddonwildaxe_)) + sizeof(rulestype_));
}

GameType::~GameType() {
  // @@protoc_insertion_point(destructor:serverMessageSystem.GameType)
  SharedDtor();
}

void GameType::SharedDtor() {
}

void GameType::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameType& GameType::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_GameType_serverMessageSystem_2eproto.base);
  return *internal_default_instance();
}


void GameType::Clear() {
// @@protoc_insertion_point(message_clear_start:serverMessageSystem.GameType)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&hasaddonwildaxe_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rulestype_) -
      reinterpret_cast<char*>(&hasaddonwildaxe_)) + sizeof(rulestype_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GameType::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<GameType*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bool hasAddonWildAxe = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        bool value = val;
        msg->set_hasaddonwildaxe(value);
        break;
      }
      // bool hasAddonClericalErrors = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        bool value = val;
        msg->set_hasaddonclericalerrors(value);
        break;
      }
      // .serverMessageSystem.RulesType rulesType = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::serverMessageSystem::RulesType value = static_cast<::serverMessageSystem::RulesType>(val);
        msg->set_rulestype(value);
        break;
      }
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4 || tag == 0) {
          bool ok = ctx->ValidEndGroup(tag);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GameType::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:serverMessageSystem.GameType)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool hasAddonWildAxe = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &hasaddonwildaxe_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool hasAddonClericalErrors = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &hasaddonclericalerrors_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .serverMessageSystem.RulesType rulesType = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_rulestype(static_cast< ::serverMessageSystem::RulesType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:serverMessageSystem.GameType)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:serverMessageSystem.GameType)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GameType::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:serverMessageSystem.GameType)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool hasAddonWildAxe = 1;
  if (this->hasaddonwildaxe() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->hasaddonwildaxe(), output);
  }

  // bool hasAddonClericalErrors = 2;
  if (this->hasaddonclericalerrors() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->hasaddonclericalerrors(), output);
  }

  // .serverMessageSystem.RulesType rulesType = 3;
  if (this->rulestype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->rulestype(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:serverMessageSystem.GameType)
}

::google::protobuf::uint8* GameType::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:serverMessageSystem.GameType)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool hasAddonWildAxe = 1;
  if (this->hasaddonwildaxe() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->hasaddonwildaxe(), target);
  }

  // bool hasAddonClericalErrors = 2;
  if (this->hasaddonclericalerrors() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->hasaddonclericalerrors(), target);
  }

  // .serverMessageSystem.RulesType rulesType = 3;
  if (this->rulestype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->rulestype(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serverMessageSystem.GameType)
  return target;
}

size_t GameType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serverMessageSystem.GameType)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool hasAddonWildAxe = 1;
  if (this->hasaddonwildaxe() != 0) {
    total_size += 1 + 1;
  }

  // bool hasAddonClericalErrors = 2;
  if (this->hasaddonclericalerrors() != 0) {
    total_size += 1 + 1;
  }

  // .serverMessageSystem.RulesType rulesType = 3;
  if (this->rulestype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->rulestype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameType::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serverMessageSystem.GameType)
  GOOGLE_DCHECK_NE(&from, this);
  const GameType* source =
      ::google::protobuf::DynamicCastToGenerated<GameType>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serverMessageSystem.GameType)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serverMessageSystem.GameType)
    MergeFrom(*source);
  }
}

void GameType::MergeFrom(const GameType& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serverMessageSystem.GameType)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.hasaddonwildaxe() != 0) {
    set_hasaddonwildaxe(from.hasaddonwildaxe());
  }
  if (from.hasaddonclericalerrors() != 0) {
    set_hasaddonclericalerrors(from.hasaddonclericalerrors());
  }
  if (from.rulestype() != 0) {
    set_rulestype(from.rulestype());
  }
}

void GameType::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serverMessageSystem.GameType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameType::CopyFrom(const GameType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serverMessageSystem.GameType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameType::IsInitialized() const {
  return true;
}

void GameType::Swap(GameType* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameType::InternalSwap(GameType* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(hasaddonwildaxe_, other->hasaddonwildaxe_);
  swap(hasaddonclericalerrors_, other->hasaddonclericalerrors_);
  swap(rulestype_, other->rulestype_);
}

::google::protobuf::Metadata GameType::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_serverMessageSystem_2eproto);
  return ::file_level_metadata_serverMessageSystem_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ClientEnteringRequest::InitAsDefaultInstance() {
  ::serverMessageSystem::_ClientEnteringRequest_default_instance_._instance.get_mutable()->gametype_ = const_cast< ::serverMessageSystem::GameType*>(
      ::serverMessageSystem::GameType::internal_default_instance());
}
class ClientEnteringRequest::HasBitSetters {
 public:
  static const ::serverMessageSystem::GameType& gametype(const ClientEnteringRequest* msg);
};

const ::serverMessageSystem::GameType&
ClientEnteringRequest::HasBitSetters::gametype(const ClientEnteringRequest* msg) {
  return *msg->gametype_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientEnteringRequest::kMessageIDFieldNumber;
const int ClientEnteringRequest::kClientNameFieldNumber;
const int ClientEnteringRequest::kEnteringRequestFieldNumber;
const int ClientEnteringRequest::kGameTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientEnteringRequest::ClientEnteringRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:serverMessageSystem.ClientEnteringRequest)
}
ClientEnteringRequest::ClientEnteringRequest(const ClientEnteringRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clientname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.clientname().size() > 0) {
    clientname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientname_);
  }
  if (from.has_gametype()) {
    gametype_ = new ::serverMessageSystem::GameType(*from.gametype_);
  } else {
    gametype_ = NULL;
  }
  ::memcpy(&messageid_, &from.messageid_,
    static_cast<size_t>(reinterpret_cast<char*>(&enteringrequest_) -
    reinterpret_cast<char*>(&messageid_)) + sizeof(enteringrequest_));
  // @@protoc_insertion_point(copy_constructor:serverMessageSystem.ClientEnteringRequest)
}

void ClientEnteringRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ClientEnteringRequest_serverMessageSystem_2eproto.base);
  clientname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&gametype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&enteringrequest_) -
      reinterpret_cast<char*>(&gametype_)) + sizeof(enteringrequest_));
}

ClientEnteringRequest::~ClientEnteringRequest() {
  // @@protoc_insertion_point(destructor:serverMessageSystem.ClientEnteringRequest)
  SharedDtor();
}

void ClientEnteringRequest::SharedDtor() {
  clientname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete gametype_;
}

void ClientEnteringRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClientEnteringRequest& ClientEnteringRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ClientEnteringRequest_serverMessageSystem_2eproto.base);
  return *internal_default_instance();
}


void ClientEnteringRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:serverMessageSystem.ClientEnteringRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clientname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && gametype_ != NULL) {
    delete gametype_;
  }
  gametype_ = NULL;
  ::memset(&messageid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&enteringrequest_) -
      reinterpret_cast<char*>(&messageid_)) + sizeof(enteringrequest_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ClientEnteringRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ClientEnteringRequest*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint32 messageID = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_messageid(value);
        break;
      }
      // string clientName = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("serverMessageSystem.ClientEnteringRequest.clientName");
        parser_till_end = ::google::protobuf::internal::StringParserUTF8;
        ::std::string* str = msg->mutable_clientname();
        str->clear();
        object = str;
        if (size > end - ptr) goto len_delim_till_end;
        auto newend = ptr + size;
        if (size) ptr = parser_till_end(ptr, newend, object, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
        break;
      }
      // .serverMessageSystem.GameCreationRequest enteringRequest = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::serverMessageSystem::GameCreationRequest value = static_cast<::serverMessageSystem::GameCreationRequest>(val);
        msg->set_enteringrequest(value);
        break;
      }
      // .serverMessageSystem.GameType gameType = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::serverMessageSystem::GameType::_InternalParse;
        object = msg->mutable_gametype();
        if (size > end - ptr) goto len_delim_till_end;
        auto newend = ptr + size;
        bool ok = ctx->ParseExactRange({parser_till_end, object},
                                       ptr, newend);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
        ptr = newend;
        break;
      }
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4 || tag == 0) {
          bool ok = ctx->ValidEndGroup(tag);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ClientEnteringRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:serverMessageSystem.ClientEnteringRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 messageID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &messageid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string clientName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_clientname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->clientname().data(), static_cast<int>(this->clientname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "serverMessageSystem.ClientEnteringRequest.clientName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .serverMessageSystem.GameCreationRequest enteringRequest = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_enteringrequest(static_cast< ::serverMessageSystem::GameCreationRequest >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .serverMessageSystem.GameType gameType = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_gametype()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:serverMessageSystem.ClientEnteringRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:serverMessageSystem.ClientEnteringRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ClientEnteringRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:serverMessageSystem.ClientEnteringRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 messageID = 1;
  if (this->messageid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->messageid(), output);
  }

  // string clientName = 2;
  if (this->clientname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->clientname().data(), static_cast<int>(this->clientname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "serverMessageSystem.ClientEnteringRequest.clientName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->clientname(), output);
  }

  // .serverMessageSystem.GameCreationRequest enteringRequest = 3;
  if (this->enteringrequest() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->enteringrequest(), output);
  }

  // .serverMessageSystem.GameType gameType = 4;
  if (this->has_gametype()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::gametype(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:serverMessageSystem.ClientEnteringRequest)
}

::google::protobuf::uint8* ClientEnteringRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:serverMessageSystem.ClientEnteringRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 messageID = 1;
  if (this->messageid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->messageid(), target);
  }

  // string clientName = 2;
  if (this->clientname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->clientname().data(), static_cast<int>(this->clientname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "serverMessageSystem.ClientEnteringRequest.clientName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->clientname(), target);
  }

  // .serverMessageSystem.GameCreationRequest enteringRequest = 3;
  if (this->enteringrequest() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->enteringrequest(), target);
  }

  // .serverMessageSystem.GameType gameType = 4;
  if (this->has_gametype()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::gametype(this), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:serverMessageSystem.ClientEnteringRequest)
  return target;
}

size_t ClientEnteringRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:serverMessageSystem.ClientEnteringRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string clientName = 2;
  if (this->clientname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->clientname());
  }

  // .serverMessageSystem.GameType gameType = 4;
  if (this->has_gametype()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *gametype_);
  }

  // uint32 messageID = 1;
  if (this->messageid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->messageid());
  }

  // .serverMessageSystem.GameCreationRequest enteringRequest = 3;
  if (this->enteringrequest() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->enteringrequest());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientEnteringRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:serverMessageSystem.ClientEnteringRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientEnteringRequest* source =
      ::google::protobuf::DynamicCastToGenerated<ClientEnteringRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:serverMessageSystem.ClientEnteringRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:serverMessageSystem.ClientEnteringRequest)
    MergeFrom(*source);
  }
}

void ClientEnteringRequest::MergeFrom(const ClientEnteringRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:serverMessageSystem.ClientEnteringRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.clientname().size() > 0) {

    clientname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientname_);
  }
  if (from.has_gametype()) {
    mutable_gametype()->::serverMessageSystem::GameType::MergeFrom(from.gametype());
  }
  if (from.messageid() != 0) {
    set_messageid(from.messageid());
  }
  if (from.enteringrequest() != 0) {
    set_enteringrequest(from.enteringrequest());
  }
}

void ClientEnteringRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:serverMessageSystem.ClientEnteringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientEnteringRequest::CopyFrom(const ClientEnteringRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:serverMessageSystem.ClientEnteringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientEnteringRequest::IsInitialized() const {
  return true;
}

void ClientEnteringRequest::Swap(ClientEnteringRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientEnteringRequest::InternalSwap(ClientEnteringRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  clientname_.Swap(&other->clientname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(gametype_, other->gametype_);
  swap(messageid_, other->messageid_);
  swap(enteringrequest_, other->enteringrequest_);
}

::google::protobuf::Metadata ClientEnteringRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_serverMessageSystem_2eproto);
  return ::file_level_metadata_serverMessageSystem_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace serverMessageSystem
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::serverMessageSystem::GameType* Arena::CreateMaybeMessage< ::serverMessageSystem::GameType >(Arena* arena) {
  return Arena::CreateInternal< ::serverMessageSystem::GameType >(arena);
}
template<> PROTOBUF_NOINLINE ::serverMessageSystem::ClientEnteringRequest* Arena::CreateMaybeMessage< ::serverMessageSystem::ClientEnteringRequest >(Arena* arena) {
  return Arena::CreateInternal< ::serverMessageSystem::ClientEnteringRequest >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
